### ISSUE TITLE
why not using Object.assign instead?

### ISSUE THREAD

**Issue by elmasse** [shovon/mixins#1]
Hello,

I was looking at the code and it seems a bit easier to implement this with Object.assign so you can avoid looping into the objects. What do you think?

``` js
export function mixins(...mixinsList) {
    return function (target) {
        Object.assign(target.prototype, ...mixinsList);
    }
}
```

**Comment by shovon** [comment]
> What do you think?

That definitely does look great. Except, with that above code, running `npm test` yields the following error message with an exit code of 1 (error):

```
  mixins
    ✓ should apply a single mixin to a constructor
    ✓ should apply a single mixin to a class
    ✓ should apply multiple mixins to a constructor
    ✓ should apply multiple mixins to a class
    ✓ a single mixin should not modify the prototype
    1) a single mixin should not modify the class methods
    ✓ multiple mixins should not modify the prototype
    2) multiple mixins should not modify the class methods


  6 passing (121ms)
  2 failing

  1) mixins a single mixin should not modify the class methods:
     Error: expected 'troll' to equal 'foo'
      at Context.<anonymous> (test.js:67:36)

  2) mixins multiple mixins should not modify the class methods:
     Error: expected 'troll2' to equal 'foo'
      at Context.<anonymous> (test.js:92:36)
```

This is because using your code, the decorator style with ES7 classes overrides the class' method, which is not intended. So for example:

``` javascript
const myMixin = {
  fooMethod: () => 'troll'
};

@mixins(myMixin)
class Foo {
  fooMethod() {
    return 'foo';
  }
}

new Foo().fooMethod(); // returns "troll", when it should return "foo"
```

The purpose of mixins is to add common functionality to classes, but still allowing the programmer to override the injected methods and properties.

**Comment by elmasse** [comment]
@shovon ok, got it. This could be a matter of taste. IMO, the mixin as a decorator is applied _after_ the class is defined making class method plausible to be overridden.
On the other hand, I agree that might not be the case since from another perspective, you're totally right, the mixin should be applied first and the class definition will won.

Thanks for getting some time to discuss this! I have been working on a little library called cocktail.next and it does something very similar to this. Plus, it adds traits.
